baseURL = 'https://jadenarceneaux.com'
languageCode = 'en-us'
title = 'Jaden Arceneaux'
copyright = "© Jaden Arceneaux"
pagination.pagerSize = 8                           # articles per pag
# Code Highlight
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^API_ADDRESS$']

[params]
og_image = "/icon.png"
subtitle = "Software Developer and occacional writer"
description = "Software developer, occasional writer, and dedicated Neovim user based in beautiful Las Vegas, Nevada🌵"
mode = "toggle"
mathjax = true                                                # enable MathJax support
katex = true                                                  # enable KaTeX support
enableRobotsTXT = true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jadens-arc"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/jaden.svg/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jaden-arceneaux/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/jadenarceneaux/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:contact@jadenarceneaux.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

[[menu.main]]
name = "Misc"
url = "/misc"
weight = 5
