services:
  hugo:
    image: hugomods/hugo
    volumes:
      - hugo_public:/src/public
      - ./frontend:/src
    env_file: .env
    command: hugo

  express:
    image: node:latest
    restart: unless-stopped
    volumes:
      - ./backend:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run start"
    env_file: .env
    networks:
      - web_network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - hugo_public:/public
      - ./logs:/var/log/caddy
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  hugo_public:
