services:
  hugo:
    image: hugomods/hugo
    volumes:
      - ./public:/src/public
      - .:/src
    command: hugo
  caddy:
    image: caddy:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/public
